# Generated by Django 5.0.3 on 2024-04-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='choices',
            field=models.ManyToManyField(blank=True, related_name='multiple_choices', to='survey.choice'),
        ),
    ]
