# Generated by Django 5.0.3 on 2024-04-15 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_answer_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='text',
            new_name='text1',
        ),
        migrations.AddField(
            model_name='choice',
            name='text2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='text3',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('TX', 'テキスト入力'), ('SC', 'ラジオボタン'), ('MC', '複数選択可'), ('RS', '評価スケール')], default='TX', max_length=2),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(max_length=255)),
                ('text2', models.CharField(max_length=255)),
                ('text3', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='survey.question')),
            ],
        ),
    ]
