# Generated by Django 5.0.3 on 2024-04-16 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_remove_survey_questions_question_survey_survey_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='user',
            new_name='profile',
        ),
    ]
