# Generated by Django 5.0.3 on 2024-04-23 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_rename_user_survey_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='text1',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='text2',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='text3',
        ),
        migrations.AddField(
            model_name='answer',
            name='rating_score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.rating'),
        ),
        migrations.AddField(
            model_name='rating',
            name='rating_score',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('TX', 'テキスト入力'), ('SC', '単一選択式'), ('MC', '複数選択式'), ('RS', '評価スケール(1~5の評価スコア)')], default='TX', max_length=2),
        ),
        migrations.AlterField(
            model_name='rating',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_score', to='survey.question'),
        ),
    ]
