# Generated by Django 5.0.3 on 2024-05-06 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_remove_answer_rating_remove_rating_text1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='text1',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='text2',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='text3',
        ),
    ]
