# Generated by Django 5.0.3 on 2024-05-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_rename_text1_choice_text_remove_choice_text2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='rating_score',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='choices',
            new_name='multiple_choices',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
